blueprint:
  name: "WS Core: Frost Alert"
  description: >-
    Send a notification when the temperature drops below a threshold.
    Uses the Weather Station Core temperature sensor with configurable
    threshold and notification target.
  domain: automation
  input:
    temperature_entity:
      name: Temperature sensor
      description: Your WS Core temperature entity
      default: sensor.ws_temperature
      selector:
        entity:
          domain: sensor
          device_class: temperature
    threshold:
      name: Frost threshold
      description: Temperature below which to trigger the alert (°C)
      default: 2.0
      selector:
        number:
          min: -10
          max: 10
          step: 0.5
          unit_of_measurement: "°C"
    notify_target:
      name: Notification service
      description: "The notification service to call (e.g. notify.mobile_app_phone)"
      default: notify.persistent_notification
      selector:
        text:

trigger:
  - platform: numeric_state
    entity_id: !input temperature_entity
    below: !input threshold
    for:
      minutes: 5

condition: []

action:
  - service: !input notify_target
    data:
      title: "🥶 Frost Warning"
      message: >-
        Temperature has dropped to {{ states(trigger.entity_id) }}°C.
        Protect sensitive plants and check exposed pipes.
