blueprint:
  name: "WS Core: Rain Notification"
  description: >-
    Send a notification when rain starts (rain rate exceeds threshold)
    or when rain probability exceeds a configurable level.
  domain: automation
  input:
    rain_rate_entity:
      name: Rain rate sensor
      description: Your WS Core filtered rain rate entity
      default: sensor.ws_rain_rate
      selector:
        entity:
          domain: sensor
    rain_probability_entity:
      name: Rain probability sensor
      description: Your WS Core combined rain probability entity
      default: sensor.ws_rain_probability_combined
      selector:
        entity:
          domain: sensor
    rain_rate_threshold:
      name: Rain rate threshold (mm/h)
      description: Rain rate above which to trigger
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 20
          step: 0.1
          unit_of_measurement: "mm/h"
    probability_threshold:
      name: Rain probability threshold (%)
      description: Probability above which to trigger (set to 100 to disable)
      default: 80
      selector:
        number:
          min: 50
          max: 100
          step: 5
          unit_of_measurement: "%"
    notify_target:
      name: Notification service
      default: notify.persistent_notification
      selector:
        text:

trigger:
  - platform: numeric_state
    entity_id: !input rain_rate_entity
    above: !input rain_rate_threshold
    id: rain_started
  - platform: numeric_state
    entity_id: !input rain_probability_entity
    above: !input probability_threshold
    id: rain_likely
    for:
      minutes: 10

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: rain_started
        sequence:
          - service: !input notify_target
            data:
              title: "ðŸŒ§ï¸ Rain Detected"
              message: >-
                Rain rate: {{ states(trigger.entity_id) }} mm/h.
                Close windows and bring in laundry!
      - conditions:
          - condition: trigger
            id: rain_likely
        sequence:
          - service: !input notify_target
            data:
              title: "ðŸŒ§ï¸ Rain Expected"
              message: >-
                Rain probability is {{ states(trigger.entity_id) }}%.
                Consider bringing in laundry or closing skylights.
